SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE dbo.MyProc
AS
BEGIN TRY

	BEGIN TRANSACTION
	INSERT INTO dbo.ThisTableDoesNotExist DEFAULT VALUES;
	COMMIT TRANSACTION;

END TRY
BEGIN CATCH
	IF @@TRANCOUNT > 0
	BEGIN
		ROLLBACK TRANSACTION;
	END;
	--THROW 50000, 'dbo.ThisTableDoesNotExist does not exists. Transaction rolled back.', 1;
END CATCH;
GO
