SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[AEL_Check_Processes_Running] (
		[id]         [int] IDENTITY(1, 1) NOT NULL,
		[RESULT]     [nvarchar](max) COLLATE French_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE [dbo].[AEL_Check_Processes_Running] SET (LOCK_ESCALATION = TABLE)
GO
